//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reviser.Files.SoJ {
    using System;
    
    
    /// <summary>
    ///   Classe di risorse fortemente tipizzata per la ricerca di stringhe localizzate e così via.
    /// </summary>
    // Questa classe è stata generata automaticamente dalla classe StronglyTypedResourceBuilder.
    // tramite uno strumento quale ResGen o Visual Studio.
    // Per aggiungere o rimuovere un membro, modificare il file con estensione ResX ed eseguire nuovamente ResGen
    // con l'opzione /str oppure ricompilare il progetto VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class GS6 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GS6() {
        }
        
        /// <summary>
        ///   Restituisce l'istanza di ResourceManager nella cache utilizzata da questa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Reviser.src.Files.GMDv2.GS6", typeof(GS6).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Esegue l'override della proprietà CurrentUICulture del thread corrente per tutte le
        ///   ricerche di risorse eseguite utilizzando questa classe di risorse fortemente tipizzata.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Actor.
        /// </summary>
        internal static string Actor {
            get {
                return ResourceManager.GetString("Actor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Ahlbi.
        /// </summary>
        internal static string Ahlbi {
            get {
                return ResourceManager.GetString("Ahlbi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Amara.
        /// </summary>
        internal static string Amara {
            get {
                return ResourceManager.GetString("Amara", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Andistan&apos;dhin.
        /// </summary>
        internal static string Andistandhin {
            get {
                return ResourceManager.GetString("Andistandhin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Apollo.
        /// </summary>
        internal static string Apollo {
            get {
                return ResourceManager.GetString("Apollo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Armie.
        /// </summary>
        internal static string Armie {
            get {
                return ResourceManager.GetString("Armie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Athena.
        /// </summary>
        internal static string Athena {
            get {
                return ResourceManager.GetString("Athena", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Atishon.
        /// </summary>
        internal static string Atishon {
            get {
                return ResourceManager.GetString("Atishon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Bailiff.
        /// </summary>
        internal static string Bailiff {
            get {
                return ResourceManager.GetString("Bailiff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Beh&apos;leeb.
        /// </summary>
        internal static string Behleeb {
            get {
                return ResourceManager.GetString("Behleeb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Betty.
        /// </summary>
        internal static string Betty {
            get {
                return ResourceManager.GetString("Betty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Blackquill.
        /// </summary>
        internal static string Blackquill {
            get {
                return ResourceManager.GetString("Blackquill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Bonny.
        /// </summary>
        internal static string Bonny {
            get {
                return ResourceManager.GetString("Bonny", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Bucky.
        /// </summary>
        internal static string Bucky {
            get {
                return ResourceManager.GetString("Bucky", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Child.
        /// </summary>
        internal static string Child {
            get {
                return ResourceManager.GetString("Child", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Datz.
        /// </summary>
        internal static string Datz {
            get {
                return ResourceManager.GetString("Datz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Dhurke.
        /// </summary>
        internal static string Dhurke {
            get {
                return ResourceManager.GetString("Dhurke", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Dr. Buff.
        /// </summary>
        internal static string DrBuff {
            get {
                return ResourceManager.GetString("DrBuff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Edgeworth.
        /// </summary>
        internal static string Edgeworth {
            get {
                return ResourceManager.GetString("Edgeworth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Ellen.
        /// </summary>
        internal static string Ellen {
            get {
                return ResourceManager.GetString("Ellen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Ema.
        /// </summary>
        internal static string Ema {
            get {
                return ResourceManager.GetString("Ema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a  .
        /// </summary>
        internal static string Empty {
            get {
                return ResourceManager.GetString("Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Gallery.
        /// </summary>
        internal static string Gallery {
            get {
                return ResourceManager.GetString("Gallery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Ga&apos;ran.
        /// </summary>
        internal static string Garan {
            get {
                return ResourceManager.GetString("Garan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Geiru.
        /// </summary>
        internal static string Geiru {
            get {
                return ResourceManager.GetString("Geiru", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Gloomsbury.
        /// </summary>
        internal static string Gloomsbury {
            get {
                return ResourceManager.GetString("Gloomsbury", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Guard.
        /// </summary>
        internal static string Guard {
            get {
                return ResourceManager.GetString("Guard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Ihmus.
        /// </summary>
        internal static string Ihmus {
            get {
                return ResourceManager.GetString("Ihmus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Inga.
        /// </summary>
        internal static string Inga {
            get {
                return ResourceManager.GetString("Inga", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Jinxie.
        /// </summary>
        internal static string Jinxie {
            get {
                return ResourceManager.GetString("Jinxie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Jove.
        /// </summary>
        internal static string Jove {
            get {
                return ResourceManager.GetString("Jove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Judge.
        /// </summary>
        internal static string Judge {
            get {
                return ResourceManager.GetString("Judge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Kisegawa.
        /// </summary>
        internal static string Kisegawa {
            get {
                return ResourceManager.GetString("Kisegawa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Klavier.
        /// </summary>
        internal static string Klavier {
            get {
                return ResourceManager.GetString("Klavier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Lady.
        /// </summary>
        internal static string Lady {
            get {
                return ResourceManager.GetString("Lady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Larry.
        /// </summary>
        internal static string Larry {
            get {
                return ResourceManager.GetString("Larry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Maid.
        /// </summary>
        internal static string Maid {
            get {
                return ResourceManager.GetString("Maid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Man.
        /// </summary>
        internal static string Man {
            get {
                return ResourceManager.GetString("Man", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Maya.
        /// </summary>
        internal static string Maya {
            get {
                return ResourceManager.GetString("Maya", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Mr. Hat.
        /// </summary>
        internal static string MrHat {
            get {
                return ResourceManager.GetString("MrHat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Mr. Reus.
        /// </summary>
        internal static string MrReus {
            get {
                return ResourceManager.GetString("MrReus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Nahyuta.
        /// </summary>
        internal static string Nahyuta {
            get {
                return ResourceManager.GetString("Nahyuta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Nayna.
        /// </summary>
        internal static string Nayna {
            get {
                return ResourceManager.GetString("Nayna", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Nichody.
        /// </summary>
        internal static string Nichody {
            get {
                return ResourceManager.GetString("Nichody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Oldbag.
        /// </summary>
        internal static string Oldbag {
            get {
                return ResourceManager.GetString("Oldbag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Old Man.
        /// </summary>
        internal static string OldMan {
            get {
                return ResourceManager.GetString("OldMan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Owen.
        /// </summary>
        internal static string Owen {
            get {
                return ResourceManager.GetString("Owen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Patches.
        /// </summary>
        internal static string Patches {
            get {
                return ResourceManager.GetString("Patches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Payne.
        /// </summary>
        internal static string Payne {
            get {
                return ResourceManager.GetString("Payne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Pearl.
        /// </summary>
        internal static string Pearl {
            get {
                return ResourceManager.GetString("Pearl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Phoenix.
        /// </summary>
        internal static string Phoenix {
            get {
                return ResourceManager.GetString("Phoenix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Phone.
        /// </summary>
        internal static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Policeman.
        /// </summary>
        internal static string Policeman {
            get {
                return ResourceManager.GetString("Policeman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Rayfa.
        /// </summary>
        internal static string Rayfa {
            get {
                return ResourceManager.GetString("Rayfa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Rebel.
        /// </summary>
        internal static string Rebel {
            get {
                return ResourceManager.GetString("Rebel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Relative.
        /// </summary>
        internal static string Relative {
            get {
                return ResourceManager.GetString("Relative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Reporter.
        /// </summary>
        internal static string Reporter {
            get {
                return ResourceManager.GetString("Reporter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Retinz.
        /// </summary>
        internal static string Retinz {
            get {
                return ResourceManager.GetString("Retinz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Rohl.
        /// </summary>
        internal static string Rohl {
            get {
                return ResourceManager.GetString("Rohl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Royal Guard.
        /// </summary>
        internal static string RoyalGuard {
            get {
                return ResourceManager.GetString("RoyalGuard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Sarge.
        /// </summary>
        internal static string Sarge {
            get {
                return ResourceManager.GetString("Sarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Scuttlebutt.
        /// </summary>
        internal static string Scuttlebutt {
            get {
                return ResourceManager.GetString("Scuttlebutt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Shah&apos;do.
        /// </summary>
        internal static string Shahdo {
            get {
                return ResourceManager.GetString("Shahdo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Sorin.
        /// </summary>
        internal static string Sorin {
            get {
                return ResourceManager.GetString("Sorin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Staff.
        /// </summary>
        internal static string Staff {
            get {
                return ResourceManager.GetString("Staff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Tahrust.
        /// </summary>
        internal static string Tahrust {
            get {
                return ResourceManager.GetString("Tahrust", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Taifu.
        /// </summary>
        internal static string Taifu {
            get {
                return ResourceManager.GetString("Taifu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Taka.
        /// </summary>
        internal static string Taka {
            get {
                return ResourceManager.GetString("Taka", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Trucy.
        /// </summary>
        internal static string Trucy {
            get {
                return ResourceManager.GetString("Trucy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a TV.
        /// </summary>
        internal static string TV {
            get {
                return ResourceManager.GetString("TV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a U.3.N.D.0..
        /// </summary>
        internal static string U3ND0 {
            get {
                return ResourceManager.GetString("U3ND0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Uendo.
        /// </summary>
        internal static string Uendo {
            get {
                return ResourceManager.GetString("Uendo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a ???.
        /// </summary>
        internal static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Villager.
        /// </summary>
        internal static string Villager {
            get {
                return ResourceManager.GetString("Villager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Warbaa&apos;d.
        /// </summary>
        internal static string Warbaad {
            get {
                return ResourceManager.GetString("Warbaad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Widget.
        /// </summary>
        internal static string Widget {
            get {
                return ResourceManager.GetString("Widget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Woods.
        /// </summary>
        internal static string Woods {
            get {
                return ResourceManager.GetString("Woods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Youth.
        /// </summary>
        internal static string Youth {
            get {
                return ResourceManager.GetString("Youth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Zeh&apos;lot.
        /// </summary>
        internal static string Zehlot {
            get {
                return ResourceManager.GetString("Zehlot", resourceCulture);
            }
        }
    }
}
