//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reviser.Language {
    using System;
    
    
    /// <summary>
    ///   Classe di risorse fortemente tipizzata per la ricerca di stringhe localizzate e così via.
    /// </summary>
    // Questa classe è stata generata automaticamente dalla classe StronglyTypedResourceBuilder.
    // tramite uno strumento quale ResGen o Visual Studio.
    // Per aggiungere o rimuovere un membro, modificare il file con estensione ResX ed eseguire nuovamente ResGen
    // con l'opzione /str oppure ricompilare il progetto VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Restituisce l'istanza di ResourceManager nella cache utilizzata da questa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Reviser.src.Language.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Esegue l'override della proprietà CurrentUICulture del thread corrente per tutte le
        ///   ricerche di risorse eseguite utilizzando questa classe di risorse fortemente tipizzata.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a All.
        /// </summary>
        internal static string FileSelector_selectAllBtn {
            get {
                return ResourceManager.GetString("FileSelector_selectAllBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a None.
        /// </summary>
        internal static string FileSelector_selectNoneBtn {
            get {
                return ResourceManager.GetString("FileSelector_selectNoneBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Select files.
        /// </summary>
        internal static string FileSelector_WindowTitle {
            get {
                return ResourceManager.GetString("FileSelector_WindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Adding file {0}....
        /// </summary>
        internal static string GenerateReport_AddingFile {
            get {
                return ResourceManager.GetString("GenerateReport_AddingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Done!.
        /// </summary>
        internal static string GenerateReport_Done {
            get {
                return ResourceManager.GetString("GenerateReport_Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Report generated successfully..
        /// </summary>
        internal static string GenerateReport_DoneMsg {
            get {
                return ResourceManager.GetString("GenerateReport_DoneMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Next line.
        /// </summary>
        internal static string GenerateReport_NextLine {
            get {
                return ResourceManager.GetString("GenerateReport_NextLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Next lines.
        /// </summary>
        internal static string GenerateReport_NextLine_Plural {
            get {
                return ResourceManager.GetString("GenerateReport_NextLine_Plural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Previous line.
        /// </summary>
        internal static string GenerateReport_PreviousLine {
            get {
                return ResourceManager.GetString("GenerateReport_PreviousLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Previous lines.
        /// </summary>
        internal static string GenerateReport_PreviousLine_Plural {
            get {
                return ResourceManager.GetString("GenerateReport_PreviousLine_Plural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Proposal.
        /// </summary>
        internal static string GenerateReport_Proposal {
            get {
                return ResourceManager.GetString("GenerateReport_Proposal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Cancel.
        /// </summary>
        internal static string Generic_Cancel {
            get {
                return ResourceManager.GetString("Generic_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Comment.
        /// </summary>
        internal static string Generic_Comment {
            get {
                return ResourceManager.GetString("Generic_Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Error.
        /// </summary>
        internal static string Generic_Error {
            get {
                return ResourceManager.GetString("Generic_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Line ID:.
        /// </summary>
        internal static string Generic_LineID_Colon {
            get {
                return ResourceManager.GetString("Generic_LineID_Colon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Markdown File.
        /// </summary>
        internal static string Generic_MarkdownFileType {
            get {
                return ResourceManager.GetString("Generic_MarkdownFileType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a New Project.
        /// </summary>
        internal static string Generic_NewProject {
            get {
                return ResourceManager.GetString("Generic_NewProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a No.
        /// </summary>
        internal static string Generic_No {
            get {
                return ResourceManager.GetString("Generic_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a No lines found!.
        /// </summary>
        internal static string Generic_NoLinesFoundError {
            get {
                return ResourceManager.GetString("Generic_NoLinesFoundError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a OK.
        /// </summary>
        internal static string Generic_OK {
            get {
                return ResourceManager.GetString("Generic_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a DragonPunk Reviser Project.
        /// </summary>
        internal static string Generic_ProjectFileType {
            get {
                return ResourceManager.GetString("Generic_ProjectFileType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Project Settings.
        /// </summary>
        internal static string Generic_ProjectSettings {
            get {
                return ResourceManager.GetString("Generic_ProjectSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Remove.
        /// </summary>
        internal static string Generic_Remove {
            get {
                return ResourceManager.GetString("Generic_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Save.
        /// </summary>
        internal static string Generic_Save {
            get {
                return ResourceManager.GetString("Generic_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Save Project.
        /// </summary>
        internal static string Generic_SaveProject {
            get {
                return ResourceManager.GetString("Generic_SaveProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Warning.
        /// </summary>
        internal static string Generic_Warning {
            get {
                return ResourceManager.GetString("Generic_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Yes.
        /// </summary>
        internal static string Generic_Yes {
            get {
                return ResourceManager.GetString("Generic_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a All Files.
        /// </summary>
        internal static string InsertFileName_allFilesCheckBox {
            get {
                return ResourceManager.GetString("InsertFileName_allFilesCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Insert File Name.
        /// </summary>
        internal static string InsertFileName_WindowTitle {
            get {
                return ResourceManager.GetString("InsertFileName_WindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Insert Line ID.
        /// </summary>
        internal static string InsertLineID_WindowTitle {
            get {
                return ResourceManager.GetString("InsertLineID_WindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Include colors.
        /// </summary>
        internal static string LineEditor_colorCheckBox {
            get {
                return ResourceManager.GetString("LineEditor_colorCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Copy translated lines from above.
        /// </summary>
        internal static string LineEditor_copyLineBtn {
            get {
                return ResourceManager.GetString("LineEditor_copyLineBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Insert filename and line ID.
        /// </summary>
        internal static string LineEditor_insertFileLineIDBtn {
            get {
                return ResourceManager.GetString("LineEditor_insertFileLineIDBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Insert Line ID.
        /// </summary>
        internal static string LineEditor_insertLineIDBtn {
            get {
                return ResourceManager.GetString("LineEditor_insertLineIDBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Add following lines.
        /// </summary>
        internal static string LineEditor_nextLinesBtn {
            get {
                return ResourceManager.GetString("LineEditor_nextLinesBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Plain text.
        /// </summary>
        internal static string LineEditor_plainTextBtn {
            get {
                return ResourceManager.GetString("LineEditor_plainTextBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Add previous lines.
        /// </summary>
        internal static string LineEditor_prevLinesBtn {
            get {
                return ResourceManager.GetString("LineEditor_prevLinesBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Add New Line.
        /// </summary>
        internal static string LineEditor_WindowTitle_Add {
            get {
                return ResourceManager.GetString("LineEditor_WindowTitle_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Edit Line.
        /// </summary>
        internal static string LineEditor_WindowTitle_Edit {
            get {
                return ResourceManager.GetString("LineEditor_WindowTitle_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Add Line.
        /// </summary>
        internal static string MainForm_addLineBtn {
            get {
                return ResourceManager.GetString("MainForm_addLineBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Add Note.
        /// </summary>
        internal static string MainForm_addNoteBtn {
            get {
                return ResourceManager.GetString("MainForm_addNoteBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a The last file in the project was marked as complete.
        ///Do you want to generate a report?.
        /// </summary>
        internal static string MainForm_AllFilesComplete {
            get {
                return ResourceManager.GetString("MainForm_AllFilesComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Almost there!.
        /// </summary>
        internal static string MainForm_AllFilesComplete_Title {
            get {
                return ResourceManager.GetString("MainForm_AllFilesComplete_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a This file was marked as complete.
        ///If you want to edit it, untick it from the file list..
        /// </summary>
        internal static string MainForm_completeLabel {
            get {
                return ResourceManager.GetString("MainForm_completeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Are you sure you want to delete this line?.
        /// </summary>
        internal static string MainForm_DeleteLineWarning {
            get {
                return ResourceManager.GetString("MainForm_DeleteLineWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Are you sure you want to delete these lines?.
        /// </summary>
        internal static string MainForm_DeleteLineWarning_Plural {
            get {
                return ResourceManager.GetString("MainForm_DeleteLineWarning_Plural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Delete selected....
        /// </summary>
        internal static string MainForm_deleteSelectedToolStripMenuItem {
            get {
                return ResourceManager.GetString("MainForm_deleteSelectedToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Delete selected....
        /// </summary>
        internal static string MainForm_deleteSelectedToolStripMenuItem_Plural {
            get {
                return ResourceManager.GetString("MainForm_deleteSelectedToolStripMenuItem_Plural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Delete Line.
        /// </summary>
        internal static string MainForm_delLineBtn {
            get {
                return ResourceManager.GetString("MainForm_delLineBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Edit Line.
        /// </summary>
        internal static string MainForm_editLineBtn {
            get {
                return ResourceManager.GetString("MainForm_editLineBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Edit selected....
        /// </summary>
        internal static string MainForm_editSelectedToolStripMenuItem {
            get {
                return ResourceManager.GetString("MainForm_editSelectedToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a You can&apos;t generate a report right now, since the project is empty..
        /// </summary>
        internal static string MainForm_EmptyProjectError {
            get {
                return ResourceManager.GetString("MainForm_EmptyProjectError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Generate Report.
        /// </summary>
        internal static string MainForm_generateReportBtn {
            get {
                return ResourceManager.GetString("MainForm_generateReportBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Some files weren&apos;t marked as complete.
        ///These files will NOT be included in the final report.
        ///Are you sure you want to continue?.
        /// </summary>
        internal static string MainForm_IncompleteFiles {
            get {
                return ResourceManager.GetString("MainForm_IncompleteFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Info on Reviser.
        /// </summary>
        internal static string MainForm_infoBtn {
            get {
                return ResourceManager.GetString("MainForm_infoBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Line.
        /// </summary>
        internal static string MainForm_line {
            get {
                return ResourceManager.GetString("MainForm_line", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Are you sure you want to mark this file as complete?
        ///This operation CAN be undone..
        /// </summary>
        internal static string MainForm_MarkAsCompleteWarning {
            get {
                return ResourceManager.GetString("MainForm_MarkAsCompleteWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Are you sure you want to mark this file as not complete?
        ///This operation CAN be undone..
        /// </summary>
        internal static string MainForm_MarkAsNotCompleteWarning {
            get {
                return ResourceManager.GetString("MainForm_MarkAsNotCompleteWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Do you want to open the new copy of the project now?.
        /// </summary>
        internal static string MainForm_OpenNewProjectCopy {
            get {
                return ResourceManager.GetString("MainForm_OpenNewProjectCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Open Project.
        /// </summary>
        internal static string MainForm_OpenProject {
            get {
                return ResourceManager.GetString("MainForm_OpenProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Original files path does not exist.
        ///Check project settings before continuing..
        /// </summary>
        internal static string MainForm_PathErrorOrig {
            get {
                return ResourceManager.GetString("MainForm_PathErrorOrig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Original files path and translated files path do not exist.
        ///Check project settings before continuing..
        /// </summary>
        internal static string MainForm_PathErrorOrigTran {
            get {
                return ResourceManager.GetString("MainForm_PathErrorOrigTran", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Translated files path does not exist.
        ///Check project settings before continuing..
        /// </summary>
        internal static string MainForm_PathErrorTran {
            get {
                return ResourceManager.GetString("MainForm_PathErrorTran", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Proposal.
        /// </summary>
        internal static string MainForm_proposal {
            get {
                return ResourceManager.GetString("MainForm_proposal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Select report destination.
        /// </summary>
        internal static string MainForm_ReportDestination {
            get {
                return ResourceManager.GetString("MainForm_ReportDestination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Save Project As....
        /// </summary>
        internal static string MainForm_saveProjectAsToolStripMenuItem {
            get {
                return ResourceManager.GetString("MainForm_saveProjectAsToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a You have unsaved changes in your project. Save?.
        /// </summary>
        internal static string MainForm_UnsavedChanges {
            get {
                return ResourceManager.GetString("MainForm_UnsavedChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a DragonPunk Reviser.
        /// </summary>
        internal static string MainForm_WindowTitle {
            get {
                return ResourceManager.GetString("MainForm_WindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Add note to.
        /// </summary>
        internal static string NoteEditor_WindowTitle_Add {
            get {
                return ResourceManager.GetString("NoteEditor_WindowTitle_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Edit note for.
        /// </summary>
        internal static string NoteEditor_WindowTitle_Edit {
            get {
                return ResourceManager.GetString("NoteEditor_WindowTitle_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Add.
        /// </summary>
        internal static string OtherLinesEditor_addBtn {
            get {
                return ResourceManager.GetString("OtherLinesEditor_addBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Add Next Lines.
        /// </summary>
        internal static string OtherLinesEditor_WindowTitle_Add_Next {
            get {
                return ResourceManager.GetString("OtherLinesEditor_WindowTitle_Add_Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Add Previous Lines.
        /// </summary>
        internal static string OtherLinesEditor_WindowTitle_Add_Previous {
            get {
                return ResourceManager.GetString("OtherLinesEditor_WindowTitle_Add_Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Edit Next Lines.
        /// </summary>
        internal static string OtherLinesEditor_WindowTitle_Edit_Next {
            get {
                return ResourceManager.GetString("OtherLinesEditor_WindowTitle_Edit_Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Edit Previous Lines.
        /// </summary>
        internal static string OtherLinesEditor_WindowTitle_Edit_Previous {
            get {
                return ResourceManager.GetString("OtherLinesEditor_WindowTitle_Edit_Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a The file list has changed.
        ///By saving the project right now, you will lose the comments related to the files which are not in the file list anymore.
        ///Are you sure you want to continue?
        ///
        ///Clicking &quot;No&quot; will ignore the new file list and the new file paths..
        /// </summary>
        internal static string ProjectSettings_ChangedFileListWarning {
            get {
                return ResourceManager.GetString("ProjectSettings_ChangedFileListWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Project must have a name!.
        /// </summary>
        internal static string ProjectSettings_EmptyProjNameError {
            get {
                return ResourceManager.GetString("ProjectSettings_EmptyProjNameError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Select files....
        /// </summary>
        internal static string ProjectSettings_fileSelectBtn {
            get {
                return ResourceManager.GetString("ProjectSettings_fileSelectBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a First File:.
        /// </summary>
        internal static string ProjectSettings_firstFileLabel {
            get {
                return ResourceManager.GetString("ProjectSettings_firstFileLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Last File:.
        /// </summary>
        internal static string ProjectSettings_lastFileLabel {
            get {
                return ResourceManager.GetString("ProjectSettings_lastFileLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Original Files:.
        /// </summary>
        internal static string ProjectSettings_origFilesLabel {
            get {
                return ResourceManager.GetString("ProjectSettings_origFilesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Select Original Files Folder.
        /// </summary>
        internal static string ProjectSettings_OrigFolderSelect {
            get {
                return ResourceManager.GetString("ProjectSettings_OrigFolderSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Project Name:.
        /// </summary>
        internal static string ProjectSettings_projNameLabel {
            get {
                return ResourceManager.GetString("ProjectSettings_projNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Project Type:.
        /// </summary>
        internal static string ProjectSettings_projTypeLabel {
            get {
                return ResourceManager.GetString("ProjectSettings_projTypeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Translated Files:.
        /// </summary>
        internal static string ProjectSettings_tranFilesLabel {
            get {
                return ResourceManager.GetString("ProjectSettings_tranFilesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Select Translated Files Folder.
        /// </summary>
        internal static string ProjectSettings_TranFolderSelect {
            get {
                return ResourceManager.GetString("ProjectSettings_TranFolderSelect", resourceCulture);
            }
        }
    }
}
